[project]
name = "pythonprotector"
version = "2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "command-runner>=1.7.4",
    "cryptography>=45.0.3",
    "discord_webhook>=1.1.0",
    "httpx>=0.28.1",
    "humanize>=4.12.3",
    "loguru>=0.7.3",
    "observable>=1.0.3",
    "psutil>=7.0.0",
    "py-cpuinfo>=9.0.0",
    "pywin32>=310",
    "requests>=2.31.0",
    "setuptools>=80.9.0",
    "WMI>=1.5.1",
    "Pillow>=11.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pythonprotector"]

[dependency-groups]
dev = ["black", "autopep8", "autoflake"]
